apiVersion: apps/v1
kind: Deployment
metadata:
  name: polyglot
spec:
  selector:
    matchLabels:
      app: polyglot-server
  replicas: 2
  template:
    metadata:
      labels:
        app: polyglot-server
    spec:
      containers:
        - name: hello-world
          image: cloudson/polyglot:v2
          ports:
            - containerPort: 8080
              protocol: TCP