name: CI
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16


    - name: Build linux
      run:  go build -o polyglot main.go
    
    - uses: actions/upload-artifact@master
      name: Generating artifact
      with:
        name: polyglot-linux64
        path: ./polyglot
    
  tests:
    needs: build
    name: Automated tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run tests
      run: go test ./cmd ./source ./language ./repository -v

    - name: Run polyglot
      run: go run main.go --username=filhodanuvem --log=info


  packaging:
    needs: tests
    name: packaging
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - uses: docker/login-action@v1
      name: Docker login 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
       
    - name: Docker push registry
      run: ./scripts/build.sh
  
  
      